# Generated by Django 2.2.10 on 2020-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='site_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
