# Generated by Django 3.0.5 on 2020-04-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitehandler', '0002_auto_20200314_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
